[tool.poetry]
name = "estimation-quiz"
version = "0.1.0"
description = "An estimation quiz"
authors = ["Peter Rasmussen <pmrrasmussen@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
django = "^5.1.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
