# Generated by Django 4.2.1 on 2023-05-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answer_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
